name: Protected

on: pull_request

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: needs-approval
    steps:
      - name: demo
        env:
          SECRET: ${{ secrets.SuperDuperSecret }}
        run: |
          echo "I can have secrets: $SECRET"