name: Protected

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: demo
        env:
          SECRET: ${{ secrets.SuperDuperSecret }}
        run: |
          echo "I can't have secrets: $SECRET"